version: 2.1

executors:
  default:
    working_directory: ~/bookstore
    description: BookStore
    docker:
      - image: circleci/ruby:2.7.1
        environment:
          DATABASE_URL: "postgres://localhost/test-postgresql"
          PGHOST: 127.0.0.1
      - image: circleci/postgres:9.6.9
        environment:
          POSTGRES_USER: circleci
          POSTGRES_PASSWORD: ""

caches:
  - &bundle_cache_full v1-bookstore-{{ checksum "Gemfile.lock" }}
  - &bundle_cache v1-bookstore
  - &yarn_cache_full v1-book_store-{{ checksum "yarn.lock" }}
  - &yarn_cache v1-book_store

commands:
  setup_environment:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *bundle_cache_full
            - *bundle_cache
      - restore_cache:
          keys:
            - *yarn_cache_full
            - *yarn_cache
      - run:
          name: Installing bundler dependencies
          command: bundle install --path vendor/bundle
      - run:
          name: Installing npm packages
          command: yarn install --path node_modules
      - save_cache:
          paths:
            - vendor/bundle
          key: *bundle_cache_full
      - save_cache:
          paths:
            - node_modules
          key: *yarn_cache_full
      - run:
          name: Database setup
          command: rake db:create
  run_linters:
    description: command to start linters
    steps:
      - run:
          name: rubocop
          command: bundle exec rubocop
  run_specs:
    steps:
      - run:
          name: run specs
          command: |
            bundle exec rspec --format progress \
                              --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec/rspec.xml
          when: always
      - store_test_results:
          path: /tmp/test-results/rspec/
jobs:
  lintering:
    executor: default
    steps:
      - defaults
      - run_linters
  run_specs:
    executor: default
    steps:
      - defaults
      - run_specs

workflows:
  version: 2
  build:
    jobs:
      - lintering
      - run_specs:
          requires:
            - lintering